leanprover-community/leanprover-community.github.io

templates/contribute/style.md
Update the section on copyright headers and mention module docstrings.
=> refactor(templates/contribute/style.md): mention module docstrings

templates/theories.md, templates/theories/linear_algebra.md
As requested by @PatrickMassot, I wrote a file about the definitions related to linear algebra (at least, the ones I'm aware of).
=> docs(theories): list definitions related to linear algebra

templates/theories/linear_algebra.md
This PR applies the suggestions made for PR #17. I can't figure out how to re-open the original pull request, so I made a new one.
Co-authored-by: Patrick Massot <patrickmassot@free.fr>
=> docs(theories/linear_algebra): apply suggestions from PR

templates/file-not-found.md
WIP. Please help fill this out!
Zulip: https://leanprover.zulipchat.com/#narrow/stream/113489-new-members/topic/Cannot.20Import.20topology.2Ebasic
See also leanprover-community/lean#253.
=> help page for "file not found" errors

data/overview.yaml
Added topics from Aggregation sections 5 and on. Still need to refine definitions and eliminate redundancies.
=> Added Aggregation 5+

data/overview.yaml
I think that 1.2&4 were the parts missing from the agreg program.
=> overview: add 1.2 & 4 from agreg program with minor fixes

data/overview.yaml
In parallel of the #26 ; I added some links.
I'll continue to add many links and think it's a good idea to let it open, as people can join and add links.
Maybe, it could be a branch of the repository so that everyone can easily do changes if they have commit access. Or I can just give commit access to my fork.
=> Overview: backfill some links & more wording

data/overview.yaml, make_site.py, templates/overview.html
This PR adds the feature to hide/show to-do elements or done elements in our list. :)
It also smartly hide big lists if they contain no "done" elements.
i.e. a section will be shown if it contains *AT LEAST* one done element, otherwise, it'll just disappear.
=> Show/hide (todo || done)

data/overview.yaml, templates/_base.html
It brings LaTeX to the list! With macros support.
=> LaTeX/Overview: Add it with macros & examples

templates/overview.html
=> overview: do not use // but /

templates/overview.html
Small fix (and a test of PR'ing though github)
=> fix (wording in undegraduate math in mathlib page)

data/overview.yaml
This needs more work, but seems like lot's of people are working on this, so didn't want to wait for it to be "perfect".
=> feature (cleanups in overview.yaml)

data/overview.yaml
I don't know how to check to see if I made any typos.
I think this might be all we have.
=> bilinear and quadratic forms

data/overview.yaml
=> more on rings

make_site.py
This makes Google happier about indexing and lets us see some basic stats.
=> add Google authentication

data/formalizations.yaml
I was tempted to add Oxford commas also, but restrained myself
=> remove first names from formalization card for consistency

templates/contribute/doc.md, templates/contribute/style.md
Zulip thread: https://leanprover.zulipchat.com/#narrow/stream/113488-general/topic/mathlib.20file.20authorship/near/200820551
=> add info about authorship, recommend putting imports on their own lines

data/100.yaml
This entry points to the wrong theorem called `sum_two_squares`.
=> fix(data/100): correct decl for item 20

templates/install/project.md
Add detailed steps/instructions for contributing to mathlib. (Copied from Patrick's Zulip messgae)
=> doc(Update project.md)

make_site.py, templates/_base.html, templates/_markdown.html, templates/mathlib_stats.html, templates/meet.html, templates/papers.html, templates/undergrad.html, templates/undergrad_todo.html
=> Gives titles to pages

templates/contribute/index.md
=> Add section "working with existing PRs"

lean.bib
Copies a few references that are being removed from the MS Lean site, and updates a few others with conference info. (Official citations/DOIs/etc aren't available yet so I've left the arxiv links for now.)
=> update bib file

data/100.yaml
I didn't know if I should put me or "mathlib" as the author, what do you think ?
=> Harmonic Series Divergence is completed

make_site.py, templates/mathlib_stats.html
=> display decl counts on stats page

templates/contribute/style.md
Two paragraphs described situations where unconventional indenting was allowed/encouraged. In practice we haven't been using these rules, so it's best to remove them.
https://leanprover.zulipchat.com/#narrow/stream/113488-general/topic/style.20guide
=> chore(contribute/style): remove unnecessary paras

templates/contribute/style.md
this is also what it says in the paragraph before
=> remove line break before import

data/overview.yaml, data/undergrad.yaml
=> rename measure_theory.measure_space in yaml files

data/100.yaml
This has been in mathlib for a month, but didn't get added to this
list when it was added to mathlib.
=> feat(data/100): Formula for Pythagorean Triples

templates/ci.md, templates/install/project.md
Describes and links to the leanprover-contrib CI scripts. These scripts (and leanprover-contrib) will evolve over the next months as I have time, but I think they're useful as-is and worth publicizing.
=> info about CI scripts

data/menus.yaml
Whether or not these are displayed as a sidebar or top menus, here are some suggestions for ordering and organizing! Very open to comments.
This is a PR into the `navpanel` branch.
=> reorganizing menu items

css/lean.css, scss/lean.scss, templates/100.html, templates/mathlib_stats.html
=> Some style tweaks

templates/contribute/style.md
Based off a discussion at https://leanprover.zulipchat.com/#narrow/stream/116395-maths/topic/Explicit.20hypothesis.20vs.20implication.20hypothesis.20convention.
This convention could nevertheless be expanded upon.
=> contribute/style: Convention for placing hypotheses before colon

templates/mwe.md
Been seeing this on Zulip recently.
=> clarify "goal state" MWEs

templates/leanproject.md
[Zulip thread](https://leanprover.zulipchat.com/#narrow/stream/113489-new-members/topic/leanproject.20upgrade-mathlib)
=> leanproject.md: specify Lean 3, discourage global mathlib, remind VS Code users to restart Lean

templates/extras/simp.md
I rewrote the (quite crappy) simp doc. It's now a bit less crappy. I wrote the original version when I was learning how to use `simp` and had no idea what was important.
=> complete rewrite of simp.md

templates/contribute/doc.md
=> contribute/doc.md: add section on LaTeX and Markdown

templates/contribute/doc.md
=> contribute/doc.md: new section on citations

templates/extras/simp.md
As discussed on [zulip](https://leanprover.zulipchat.com/#narrow/stream/113489-new-members/topic/custom.20simp-sets) :)
=> Add a mention of simpsets

data/maintainers.yaml
@cipher1024 does this look good to you?
=> update Simon and Rob's jobs

templates/install/windows.md
the name of a setting has changed
=> Update windows instructions after microsoft/vscode#118790

templates/install/macos.md, templates/install/macos_details.md
Corresponds with leanprover-community/mathlib-tools#108.
=> Update the macOS detailed install instructions to recommend Homebrew.

templates/leanproject.md
I kept it short as the page is already a lot of information
=> Add a bit of doc about removing imports

lean.bib
Things got renormalized, so the diff is hard to read. Look at the second and third commits.
=> add CICM papers and others to the bibliography

templates/learn.md
Added lean-for-hackers in a new "Miscellaneous resources" header.
=> Added lean-for-hackers

lean.bib
As discussed at https://leanprover.zulipchat.com/#narrow/stream/113488-general/topic/Jaccard.20distance/near/261071816
=> Add Jaccard distance paper

templates/glossary.md
(via https://leanprover.zulipchat.com/#narrow/stream/236604-Zulip-meta/topic/Suggested.20words.20for.20linkify )
=> Mention the Lean projects page in the leanproject glossary entry

data/menus.yaml, templates/tips_and_tricks.md
For tips to help development that don't quite fit anywhere else, as suggested on Zulip (https://leanprover.zulipchat.com/#narrow/stream/113488-general/topic/Tips.20and.20tricks/near/265408881)
Suggestions/additions welcome! I just put something rough together based on some old Zulip posts I wrote so far.
=> Add Tips and Tricks page

lean.bib
I wasn't able to run `bibtool` on this as it is not available on windows.
=> Add my Geometric Algebra paper

data/events.yaml
This adds two educational meetings and the upcoming IPAM meeting on Machine Assisted Proofs to the events page.
=> add three meetings

templates/extras/calc.md
Make first example complete and fill out explanation.
Please review carefully: new lean-er contribution, feedback and suggestions very welcome.
=> Improve explanation of calc+feedback

templates/learn.md
I was sloppy and did not pay attention to the order.
=> Fix order of meetings

templates/install/macos.md, templates/install/macos_details.md
=> Update brew package name (elan -> elan-init)

templates/theories/linear_algebra.md
=> fix some dead links on linear algebra page

templates/theories/category_theory.md
=> fix dead links on category-theory page

templates/learn.md
=> Broken link in learn.md

templates/tips_and_tricks.md
From [zulip](https://leanprover.zulipchat.com/#narrow/stream/113488-general/topic/deterministic.20timeout/near/307883429)
=> add shortcut for getting to settings

templates/undergrad.html, templates/undergrad_todo.html
This code wasn't previously exercised, and the update to the yaml file broke it.
CI should test this.
=> Fix the build

data/courses.yaml
A couple more courses from 
https://leanprover.zulipchat.com/#narrow/stream/187764-Lean-for-teaching/topic/Lean.20courses.20around.20the.20world
and adjust wording describing my own.
=> more courses for `courses.yaml`

data/events.yaml
Add an entry for the "Formalisation of Mathematics:
Workshop for Women and Mathematicians of Minority Gender" strategic workshop at ICMS. The workshop website will be updated when available.
=> Add ICMS workshop

make_site.py, templates/mathlib-overview.html, templates/undergrad.html, templates/undergrad_todo.html
Depends on:
* https://github.com/leanprover-community/mathlib4/pull/6043
=> Link to mathlib4 decls in undergrad/overview/100 theorems

templates/mwe.md
Update mwe.md to match the lean4 infrastructure.
=> feat: update mwe.md to lean4

make_site.py
=> Fix doc-gen integration

data/courses.yaml
New course - Universitat de València
=> New course - Universitat de València

data/teams.yaml
Not much else to say, other than I hope to have modified the correct file in the correct place!
=> Add myself as reviewer in data/teams.yaml

data/events.yaml
=> add icms session to events.yaml

lean.bib
Fixed one curly bracket in a name.
=> fixed one name

data/teams.yaml
Adding myself to reviewers (and fixing a tiny formatting inconsistency with Michael Stoll's entry)
=> Add David Loeffler to reviewers list

data/courses.yaml
* also remove almost-unused website for my winter course
=> add summer course at Bonn

templates/learn.md
Adding a link to the Robo game
=> adding new lean game server links

deploy.sh, mistletoe_renderer.py, templates/_base.html
- **wip**
- **Revert "wip"**
- **Enable rendering mermaid git graphs**
=> enable rendering mermaid graphs

data/courses.yaml
Added Lean for Scientists and Engineers
=> Added Lean for Scientists and Engineers to courses.yaml

make_site.py, templates/meet.html
=> Link to Zulip profiles from the map

templates/contribute/index.md
This is a rewrite of @YaelDillies's #481.
=> rewrite of Yael's lifecycle PR

templates/extras/calc.md
Fix the documentation about calculational proofs to work with Lean 4
=> Fix to lean 4 documentation for calculational proofs

make_site.py, templates/extras/simp.md
Also update reference to Data.Complex.Basic from mathlib3 to mathlib4.
=> fix: get mathlib4 contributors instead of mathlib3

templates/contribute/index.md
See [Zulip](https://leanprover.zulipchat.com/#narrow/stream/287929-mathlib4/topic/.23queue.20definition/near/473489297)
=> update #queue URL

data/menus.yaml, templates/get_started.md
Also remove the direct links for different operating systems from the sidebar
=> link to official Lean instructions to install Lean

data/courses.yaml
=> fix build by quoting line with stray colon

data/courses.yaml
Added course description for seminar on Lean at Duke University.
=> Duke University course

data/courses.yaml
We added lean4 a bit spontaneous as part of the exercises accompanying the course Semantics and Verification of Software.
=> Added course at RWTH Aachen

.gitignore, data/menus.yaml, make_site.py
cf. https://github.com/leanprover-community/leanprover-community.github.io/pull/558#issuecomment-2552426005
=> fix build, add 1000.html to menu

make_site.py
Proper fix for #559: depends on leanprover-community/mathlib4#20066
=> fix: fields of ThousandPlusTheorem

make_site.py
As well as a hack with the `header-data.json` file.
=> doc/chore: document `docDecls` field

templates/contribute/style.md, templates/extras/speedup.md
[Zulip](https://leanprover.zulipchat.com/#narrow/channel/345428-mathlib-reviewers/topic/request.3A.20discourage.20squeezing.20terminal.20simps.3F)
=> warn against squeezing simp calls

data/people.yaml
Thanks to @kbuzzard for the reminder!
=> Update my affiliation

data/community.md, templates/contribute/index.md
and slightly reorganize "working on mathlib" instructions
=> strengthen encouragement to use real names on Zulip

data/courses.yaml
We have a new course this year
=> Add Stanford's CS 99 to course list

data/people.yaml
French institutions love to change their names.
=> Update description of Remy Degenne

templates/get_started.md
Fixed small typo: following -> follow
=> Fixed typo

data/courses.yaml
As requested by Patrick Massot after the online event organised by Athina Thoma & Paola Iannone.
=> Course at Univ Gustave Eiffel, FR

templates/_overview-macros.html, templates/mathlib-overview.html, templates/undergrad.html
Also fixes the spacing of the parentheses for the existing occurrences.
=> mathlib-overview: support nesting like in undergrad

data/courses.yaml
Seminar supervised by Judith Ludwig and Florent Schaffhauser.
=> Add Heidelberg Computer-assisted Mathematics Seminar 2025

.gitignore, data/courses.yaml
We add a course from Fall 2024 on cryptography to `courses.yaml` and add `.DS_Store` to the `.gitignore` file.
=> Add course and update gitignore

.gitignore, data/courses.yaml
This reverts commit 01272cc9ce978d2066645a982512a984bcc8637f. There is a CI error. I will investigate further later.
=> Revert "Add course and update gitignore (#630)"

data/courses.yaml
Details of course "Proofs and Programs" taught at IISc, Bangalore, India added.
=> Added IISc course

templates/contribute/index.md
Just a start, please push more fixes here!
=> update contributor instructions for fork-based workflow

make_site.py
So we use some helper functions instead
=> fix: format_date_range doesn't work on windows

data/courses.yaml
Tried to follow the instructions to add course. If there are any issues feel free to adjust, or tell me so I can fix it.
=> Add lean course
