leanprover-community/leanprover-community.github.io

links/index.md

The missing Lean team papers were pointed out by Simon at https://leanprover.zulipchat.com/#narrow/stream/113488-general/topic/What.20is.20worth.20a.20paper.3F/near/191414285. I added also two community papers.

Update list of papers.

---

templates/contribute/index.md

The mathlib-nursery repo is no longer in active use. I suggest removing the text that mentions it.

remove mention of nursery from contribute/index.md

---

css/lean.css
make_site.py
scss/lean.scss

This PR makes markdown headings linkable like the way they are on github. Currently it's set up to look like this (adding a `#` symbol to the left):
If this is too ugly, it shouldn't be too hard to change the template.

make markdown headings linkable

---

data/100.yaml

cf. this conversation
https://leanprover.zulipchat.com/#narrow/stream/113488-general/topic/freek.2Eyaml/near/197670168

add full links to freek.yaml

---

css/lean.css
make_site.py
scss/lean.scss
templates/_base.html

This adds a navbar to the bottom of all pages generated from markdown with "Edit this page on GitHub" in the bottom right:
cf. https://github.com/leanprover-community/mathlib/pull/2676#issuecomment-628487986 by @robertylewis

add "Suggest edits to this page on GitHub" to bottom of markdown pages

---

make_site.py

I don't really care which version we link to, but there are existing links out there to leanprover-community.github.io/papers/mathlib-paper.pdf, so let's keep a copy there to be safe.
@PatrickMassot tagging you to make sure this is the only necessary change. The paper file is already there.

host mathlib paper on our own site

---

data/overview.yaml
make_site.py
templates/overview.html

Here we go, it will generate the overview page using the data in a recursive fashion, presented in a recursion fashion with very basic CSS because I have no styling sense!
It will just build a bunch of Overview objects which can be interpreted as a Nary tree for any N, leafs being nodes which does not have children.
Note I had to edit the overview, because it was not YAML-compliant, I'm relying on the implicit order, that might be suboptimal or not "perfect".
The HTML just follow the same reasoning, it looks already "quite" good.
Here's full page-wide screenshots.
I'll add https://getbootstrap.com/docs/4.4/components/collapse/#accordion-example in some seconds.
Please give me lots of feedback. :)

Overview: generate the overview.html

---

.github/workflows/build.yml
deploy.sh

This changes the GitHub actions and scripts so that all branches except for `master` and `oldsite` are built with CI. The deploy to `master` only occurs for the `newsite` branch.

ci: build all branches

---

data/100.yaml

There are many different ways this entry on the list could be
interpreted, but if we take a geometric interpretation then, given
that we now have Euclidean space, defined in such a way as to be a
metric space by definition, `inner_product_space_is_normed_group`
looks like it's the best choice for something that actually proves the
triangle inequality in a nontrivial context.

List triangle inequality as done in 100.yaml.

---

data/overview.yaml

I went through Section 6. It also displays what I think we should do. In particular:
* I moved stuff around a bit, to improve consistency
* I split a couple of items
* when an item has several targets but finding one tells you about the other, I didn't split, and indicated where to find one target. For instance, "Circular trigonometric function" links to the definition of sin. I did split circular and hyperbolic, especially since we don't have reciprocals hyperbolic trig functions
* When we can obviously express something but the definitions is not there, I didn't write anything. I think we should add those definitions to mathlib, in particular for the sake of discoverability. For instance we don't have convergent series of real numbers.
What I think I have a hard time to do is being …

overview: Section 6

---

data/overview.yaml

I added links to some newly-merged analysis facts ([#3059](https://github.com/leanprover-community/mathlib/pull/3059), [#3021](https://github.com/leanprover-community/mathlib/pull/3021), [#2660](https://github.com/leanprover-community/mathlib/pull/2660) ).  I also changed some translations that I found inelegant -- but I know that many of these may have been discussed already, so feel free to revert any.

overview.yaml: new links and some re-translations

---

.github/workflows/build.yml
css/lean.css
data/100.yaml
make_site.py
scss/lean.scss
templates/100.html

This is WIP, but posting to get comments. The doc page now generates a map from declaration name to location including type information. So we can use this map to display more info on the 100 theorems page.
Some of the links in the YAML file are broken already. I've commented these out, didn't investigate where they moved to.
TODO:
* It doesn't display when there are multiple declarations right now. This is easy enough, just takes a little restructuring of the data structure.
* Plenty of CSS/design work is needed.
* YAML entries no longer need the full path. I'm stripping everything before `#`. We can remove the unneeded info.
* Entries that are not in mathlib should have the type written explicitly to match.
If anyone would like to adopt this I'm happy to hand it over.

print types in 100 theorems list

---

templates/install/windows.md

I failed to follow the ``* Check `Add Python 3.x to PATH`.`` instruction, after which the advice about ``If it's something like `/c/Users/<user>/AppData/Local/Microsoft/WindowsApps/python`` is not helpful.

feat(install/windows): improve instructions

---

templates/install/macos.md
templates/install/macos_details.md

The simple instructions are mostly the Debian instructions with "MacOS" inserted at the right places.
The script was tested on a mostly clean machine and a clean VM, the detailed instructions were tested on a mostly clean machine.

feat(install): update MacOS installation instructions to use script

---

data/overview.yaml

"computer science and set theory" doesn't make any sense as a category.

rename "computer science and set theory" in overview

---

templates/contribute/style.md

The advice to use `/- -/` for section headers is out-of-date.

contribute/style: update comments section and link to doc requirements

---

data/community.md
templates/meet.html

Pending discussion at https://leanprover.zulipchat.com/#narrow/stream/113488-general/topic/community.20code.20of.20conduct so please don't merge this yet.
I've also moved the text about the maintainers to the .md file (and expanded it a bit). It's awkward to have the pictures generated in a separate file but I don't see a way around it. This gives us the `#` link on mouseover for the "Maintainers" heading.

add code of conduct

---

css/lean.css
make_site.py
scss/lean.scss
templates/100.html

Instead of parsing the U+E000 syntax here, we let the documentation generator render an HTML version.  Now all the names, notation, etc. are hyperlinked.  I changed the link color to black because the website blue is jarring when used this much.
Depends on https://github.com/leanprover-community/doc-gen/pull/49

New export_db.json format from docs.

---

templates/mwe.md

See [Zulip](https://leanprover.zulipchat.com/#narrow/stream/113488-general/topic/Being.20stuck.20-.3E.20MWE/near/206124531).
When people are asked to provide a `#mwe` on Zulip, they can directly see the tip about using `extract_goal` to create a `#mwe`.

Mention tactic `extract_goal` in `mwe.md`

---

templates/contribute/naming.md

Closes #109. Using HTML rather than Markdown backticks seems like an easier solution for this edge-case than digging too much into how `mistletoe` is escaping `|` characters in tables etc. ☺️

Fix dvd symbol in 'Mathlib naming conventions'

---

templates/get_started.md

This RFC PR:
1. moves the "regular install" instructions to the top
2. puts the per-OS installation links right at the top
3. simplifies the text throughout (although doesn't touch the trylean section, which is now at the end)

make installation instructions shorter

---

data/menus.yaml
templates/index.html
templates/lean_projects.html

This is stable enough to link to now, I think. At some point I'm going to move the infrastructure from the `leanprover-contrib` repo to `leanprover-community` but that shouldn't affect the display much.

link to projects page

---

lean.bib

I saw that my `ring_exp` paper only had a short description in `lean.bib`, so I added information from dblp to the two entries that could be expanded.

Expand two entries in `lean.bib`

---

templates/learn.md

This PR adds a link to the tablet edition of the Hitchhiker's guide next to the standard edition, on the "Learn Lean" page.

Link the tablet edition of the Hitchhiker's guide

---

templates/contribute/style.md

Some clarifications in the style guide.
* These rules apply for `def` and for `lemma`/`theorem`
* Indent assumptions / conclusion after a line break
* Short theorems can also fit on one line.

Clarify line breaking and indentation for theorems/definitions

---

make_site.py
robots.txt

This tells search engines not to index the demo `doc-gen` builds (see e.g. https://github.com/leanprover-community/doc-gen/pull/110)

add robots.txt

---

templates/theories/topology.md

Fixes an example that @jcreedcmu noticed to be broken.
Set complement notation changed in https://github.com/leanprover-community/lean/pull/367 and https://github.com/leanprover-community/mathlib/pull/3212.
I suspect something similar happened with set subtraction, but I have been unable to find
the exact point in history.

fix(theories/topology.md) update set complement and set subtraction notation

---

templates/meet.html

This makes the page layout a little denser.
Implemented as described at https://getbootstrap.com/docs/4.6/components/media-object
----
Before / after, showing the change applied to just the top two:

style(meet): Use bootstrap media rather than cards

---

templates/contribute/naming.md
templates/contribute/style.md
templates/theories.md
templates/theories/category_theory.md
templates/theories/linear_algebra.md
templates/theories/naturals.md
templates/theories/sets.md
templates/theories/topology.md

Normalize titles of pages in [theories/](https://github.com/leanprover-community/leanprover-community.github.io/tree/newsite/templates/theories):
- Capitalize 'Lean'
- Remove space before ':'
- Normalize capitalization
- Sync the in-page titles with those in theories.md
- Replace a non-breaking space character with a regular one
Also, apply various small Markdown fixes to pages in [theories/](https://github.com/leanprover-community/leanprover-community.github.io/tree/newsite/templates/theories) and [contribute/](https://github.com/leanprover-community/leanprover-community.github.io/tree/newsite/templates/contribute):
- Use a blank line to separate blocks (headings, paragraphs, code blocks, etc.)
- Normalize headings to the non-wrapped style (which is more prevalent in this repo)
- Add …

Normalize titles of pages in theories/

---

lean.bib

Add our paper "A formalization of Dedekind domains and class groups of global fields", to be presented at ITP 2021, to the bibliography file. Once the paper is published, I'll update the reference to a full `InProceedings`.

lean.bib: add paper on Dedekind domains and class groups

---

templates/contribute/doc.md

The code style guideline states, " Do all imports right after the header, without a line break," but here there is a line break.

fix(templates/contribute/doc): delete line break in documentation style guideline 

---

templates/theories/linear_algebra.md

Several refactors have made the linear algebra theory docs outdated. This PR updates them to the current state of mathlib.
The `bundled_basis` refactor that I am working on should not re-outdate these docs, by the way.

feat(theories): update linear algebra theory docs

---

templates/contribute/doc.md

The current [doc-strings contribute guidelines](https://leanprover-community.github.io/contribute/doc.html#doc-strings) refer to the `doc_blame` and `doc_blame!` commands which no longer exist. This is confusing for newcomers.
This PR updates the documentation to refer to the linters which replace these commands, and explains how they may be used by the reader who may not be familiar with the `lint` command.

doc(templates/contribute): update doc_blame linter documentation

---

templates/leanproject.md

This describes the new get-cache behavior, and pushes the "global mathlib install" section right to the bottom.
~~Note that this reflects the behavior only in the presence of https://github.com/leanprover-community/mathlib-tools/pull/113; right now if you run `get-cache --rev` in a non-mathlib project it will revert changes to lean files too, which seems unhelpful.~~

Update leanproject documentation

---

css/lean.css
make_site.py
scss/lean.scss
templates/papers.html

This makes it much easier to visually group the papers into the various eras.  The color for Lean 4 is derived from :four_leaf_clover:, of course.

Add a touch of color.

---

lean.bib

The link pointed to `class_number` when it should be `class-number`.

Fix incorrect class number paper link

---

templates/install/linux.md
templates/install/macos_details.md
templates/install/windows.md

Some of the installation instructions used to tell people to search for
the 'leanprover' VSCode extension. This is ambiguous since it can refer
to both 'lean' and 'lean4' (and 'lean4' seems to be listed first now).
This commit clarifies that 'lean' is the correct extension.

Clarify which VSCode extension to install

---

data/formalizations.yaml

For me, "continuum hypothesis" could mean something as weak as "we stated the continuum hypothesis" (indeed "perfectoid spaces" above it means "we stated the definition of a perfectoid space"). Of all the questions one could possibly ask about the continuum hypothesis, independence is probably the hardest one; it's a highly nontrivial piece of mathematics which got Cohen a Fields Medal. I think we should stress that this is what was done.

"continuum hypothesis" -> "independence of the continuum hypothesis"

---

templates/install/macos.md

I am updating the M1 installation description with some instructions from the "M1 Macs: Installing the Lean 3 toolchain" thread. These instructions worked for me and others as of today.

M1 installation instructions using the x86 build of Lean

---

templates/leanproject.md

This was referring to old syntax.
Thanks to Antoine Chambert-Loir for pointing this out

Fix description of reduce imports

---

templates/install/windows.md

if the username had a space, this would previously error

fix windows install instructions

---

templates/install/project.md

Many new users on Zulip are confused about what we mean by a "Lean project", and when they're instructed to create one they just make an empty folder and put their files in it.  Adding some text to explicitly say that that's not what we mean.

Add text explaining what "Lean project" means

---

templates/extras/calc.md

Explain that `calc` also exists in tactic mode, functioning like `refine calc`.
[Zulip discussion](https://leanprover.zulipchat.com/#narrow/stream/113489-new-members/topic/interactive.20transitivty.20proof/near/269144562)

doc(templates/extras): `calc` in tactic mode

---

templates/mathlib_stats.html

Putting this up for discussion. We could also consider embedding the graph, but then we'd need some way to strip the UI elements that won't scale well.
We might want this under the `leanprover-community` org if we plan to embed it.

Add a link to the import graph

---

templates/glossary.md

feat(templates/glossary): explain dot notation

---

templates/_base.html
templates/opensearch.xml
templates/search.xml

This should make supported browsers offer a "search mathlib docs" feature in the title bar.
It's not clear to me whether this will work in the mathlib doc repo, there are rumors online that it has to be at the site root.
I'll make a PR there anyway to test (https://github.com/leanprover-community/doc-gen/pull/161)

Add opensearch support to the mathlib docs

---

templates/contribute/style.md

Currently we have:
```lean
theorem nat_case {P : nat → Prop} (n : nat) (H1: P 0) (H2 : ∀ m, P (succ m)) : P n :=
```
I think this should be either:
```lean
theorem nat_case {P : nat → Prop} (n : nat) (H1 : P 0) (H2 : ∀ m, P (succ m)) : P n :=
```
or
```lean
theorem nat_case {P : nat → Prop} (n : nat) (H1: P 0) (H2: ∀ m, P (succ m)) : P n :=
```
I assume the former is correct?

Fix inconsistency in style.md

---

templates/theories/linear_algebra.md

The linear_algebra theory page references the non-existent theorem `linear_equiv_matrix`, which looks like it was deleted and renamed to `matrix.to_lin` 2 years ago [changelog link](https://mathlib-changelog.org/commit/7236084)

fix: broken links about linear maps and matrices

---

templates/contribute/style.md

We rewrite the second paragraph, so that it first explains the general rule, and then mentions natural numbers as a common usage.

doc(style): improve Normal forms section

---

data/events.yaml

Adding the BIRS workshop on formalization for cohomology theories. Future website 
is https://www.birs.ca/events/2023/5-day-workshops/23w5124.

add BIRS workshop

---

templates/contribute/doc.md

Fix the link to `analysis/calculus/cont_diff`

fix(contribute): times_cont_diff got renamed

---

data/community.md
data/zulip.md

Adjust the wording of the page describing Zulip, now that there is the "web-public" feature so that some streams can be browsed without registering.

adjust wording of section on zulip

---

data/presentation.md
templates/index.html

The current wording of the main page points readers to the overview and the CPP 2020 paper on mathlib for information on mathlib's contents.  The CPP paper is is now a bad source for such information (it describes a 140,000-line mathlib which is wrong by a factor of 7!).  I re-worded to point to the overview and blog for mathlib's contents, continuing to point to the CPP 2020 paper for "design and community organization."
I also dropped the phrase "CPP 2020", which will mean nothing to much of the target audience.  It would be good to instead add "published at CPP 2020" to the paper's own arxiv page; cc @robertylewis who is the arxiv owner of that paper.

change main page wording

---

templates/undergrad.html
templates/undergrad_todo.html

This displays further nested entries as `title (linked_entry, linked_entry, linked_entry)`

Allow deeper nesting within undergrad.yml

---

templates/install/debian.md
templates/install/debian_details.md
templates/install/linux.md
templates/install/macos.md
templates/install/macos_details.md
templates/install/project.md

Updating the install pages to Lean 4 using the new scripts from https://github.com/leanprover-community/mathlib4/pull/4965

Update installation and Lean projects instructions

---

data/courses.yaml
make_site.py
templates/courses.html

The template currently drops the "repo", "material", "tags", "notes", "summary", and "experiences" fields from courses.yaml.
The yaml also needs to be further updated with suggestions from https://leanprover.zulipchat.com/#narrow/stream/187764-Lean-for-teaching/topic/Lean.20courses.20around.20the.20world, and whatever else is missing.

feat: page about courses

---

data/presentation.md

Currently:
gives:
but if manually navigate to:
it works:

Super tiny fix dead link

---

data/menus.yaml
templates/contribute/commit.md
templates/contribute/index.md

This does two things:
1. adds a page addressing the commit conventions (i.e., PR title and description conventions) for mathlib, as the one we used to link to was in the Lean (not Lean 4!) repository. That document was copied, and then edited it slightly to reflect mathlib better, including the optional `(<scope>)` listing the files changed.
2. updates the contribution page to Lean 4, including a link to the new commit conventions page.

update the contribution page to Lean 4 and add commit conventions

---

data/events.yaml

Event name contained a colon and I forgot to add quotes. Oops!
Mends the build failure see here [https://github.com/leanprover-community/leanprover-community.github.io/actions/runs/6287865482]
"yaml.scanner.ScannerError: mapping values are not allowed here in "data/events.yaml", line 1, column 34"

Correct yaml of event name

---

data/teams.yaml

Add Ballard to maintainer and reviewer lists in data/teams.yaml

update the team lists 

---

templates/install/project.md

A very common mistake of new users is that they create a project folder themselves before cloning the repository. This often causes confusion in later steps (running `lake exe cache get` in the wrong directory, or opening the wrong directory in VSCode). I've seen new users do this on 3 different occasions now, and they got stuck at a later step.

add comment about not making a new folder

---

data/menus.yaml

Unlike the metaprogramming tutorial, I'm not totally sure these should go. Ideally they'd be updated. But not only are they about mathlib3, they're also out of date.

remove theory docs from side menu

---

templates/contribute/index.md

A URL at the end of a sentence following by a period is rendered with the period added to the URL, creating a broken link.

Update index.md URLs at end of sentence followed by period are not rendered correctly.

---

templates/contribute/tags_and_branches.md

@semorrison walked me through the process, so I went through the text to see if it is up to date, and made refinements where needed.
I removed the mentions of the latest-tag script, which I remove. Didn’t know it was so prominently advertised here. Maybe if https://github.com/leanprover/lean4/pull/3137 works nicely we can report the latest tag this way.
Also mentioned `nightly-with-mathlib`, which I guess should be the default branch point for most contributers.

Updates to Tags and Branches

---

templates/learn.md

TCIL is an mdbook about the kernel and proof export that was written as part of the FRO's push to make an external checker for Lean 4 available. Please let me know if there are an objections.

add TCIL to learning resources

---

templates/contribute/style.md

The entire body should be indented by two spaces, which means two more spaces than currently.
Zulip: https://leanprover.zulipchat.com/#narrow/stream/287929-mathlib4/topic/Is.20the.20indentation.20level.20wrong.20in.20the.20style.20guide.3F

Fix indentation of an example in the style guide

---

data/teams.yaml

I'm submitting this as prompted by @jcommelin on the "mathlib reviewers" zulip stream.
I added myself within the alphabetized first part of the list.

add David Renshaw as a mathlib reviewer

---

data/teams.yaml

Following a request by @kbuzzard, I have taken the opportunity to sort the list of reviewers alphabetically by last name.

Add Michael Stoll to reviewers in teams.yaml, sort list

---

templates/install/project.md

At least one person misread the end-of-sentence period as part of the command. Maybe this is clearer.

Try to clarify vs code command

---

templates/contribute/style.md

As [discussed on zulip](https://leanprover.zulipchat.com/#narrow/stream/287929-mathlib4/topic/Style.3A.20spacing.20between.20tactic.20name.20and.20arguments).

style guide: mention a space between tactic name and arguments

---

templates/contribute/naming.md

Per the reasoning in [mathlib4#10816](https://github.com/leanprover-community/mathlib4/pull/10816): these are confusing to newcomers, hence we try to avoid them.
They are still used somewhat in core, and in Mathlib/Logic/Basic - which is why I worded this relatively softly.

naming convention: recommend against ball and bex in mathlib

---

templates/contribute/style.md

Two more changes:
- add a section for easier linkability.
- rename `orderBot` to `instOrderBot` to reflect naming convention

Add example for nested instances to style guide

---

templates/install/project.md

The old version of lake creates a wrong `.gitignore`.
Alternatively, we use the instructions from [the wiki](https://github.com/leanprover-community/mathlib4/wiki/Using-mathlib4-as-a-dependency):
```
lake +leanprover-community/mathlib4:lean-toolchain new <your_project_name> math
```
but that will require an `elan self update` first for many users (including me).

update Lean version used for lake new

---

templates/learn.md

* Add `Formalising Mathematics` book
* Add `The Hitchhiker's Guide to Logical Verification` book (this should not go under `(Meta)-programming and tactic writing` since it's still about proving, not programming).
* Change description of `Theorem Proving in Lean`
* Remove meetings that were not aimed at beginners, but link to the event page.

feat: changes to the learn page

---

templates/install/macos_details.md

Homebrew `elan-init` lags in version and can be confusing to find. Change the detailed install instructions to reference the released installers.

chore: update MacOS instructions to remove Homebrew references

---

templates/contribute/index.md

As `scripts/mk_all.sh` is deprecated, and might even get removed with [mathlib4#14540](https://github.com/leanprover-community/mathlib4/pull/14540).

replace `scripts/mk_all.sh` with `lake exe mk_all`

---

templates/install/project.md

* Add detailed update instructions
* The hosting section was mostly there to link to `ci.html` which was removed.
* Add troubleshooting instructions when a corrupted Lean version was downloaded
* Add instructions to clean-up old Lean versions/Mathlib cache.
fixes #489

add updating and troubleshooting instructions, remove hosting

---

data/courses.yaml

The website was a signup link: as notes and videos are being posted on zulip, that seems a more useful link now.
Also removing "English" as this is the default.

chore: update details for Lean for Scientists and Engineers

---

templates/extras/calc.md

The "calc mode" page lacks ```` ``` ````.

Fix "calc mode"

---

templates/contribute/style.md

the linter checking the header matches on `Authors:` and makes sure the line doesn't end in `.`, so it would fail on the example. also make the year current, while we're at it.

make sure the example copyright header would pass CI

---

templates/contribute/naming.md

Fix typo: 
`patter` -> `pattern`
in
"describe the patter `-a * -b`."

Fix typo in naming.md

---

templates/install/project.md

The old documentation pointed to the stand alone repo. This points to the corresponding file in https://github.com/leanprover/lean4

Updates outdated link to lake documentation

---

templates/learn.md

It took me surprisingly long to find https://leanprover-community.github.io/mathlib4_docs/, and I think it's one of the best references a newcomer to Lean can rely on. I wrote a tiny blurb (feel free to reword) in the hands-on section mentioning this: previously, the only link to the API documentation was a single small one on the sidebar.

Prominently mention the API documentation 

---

templates/mathlib_stats.html

Restore the dependency graph, which used to exist for Lean 3 and was originally added in #218.

feat: add dependency graph

---

data/menus.yaml

I stumbled across Loogle recently. It doesn't appear to be mentioned on the learning resources page yet.
This also changes the link to mathlib4_docs from "API documentation" to "General documentation". I think this is a lot clearer (and is what mathlib4_docs calls itself): when I was first poking around with Lean I thought this was some sort of FFI documentation, and didn't realize it is the primary documentation page for the language.

Add Loogle to sidebar links

---

templates/contribute/naming.md
templates/contribute/pr-review.md
templates/contribute/style.md

This makes them consistent with the other documents.
While Jeremy authored these in Lean 2, they are now community-maintained documents, and listing all the authors involved isn't really that interesting.

Remove authorship and copyright from doc pages

---

templates/contribute/commit.md

As pointed out in https://github.com/leanprover-community/leanprover-community.github.io/pull/359#discussion_r1312346046, `- [ ] depends on:` should be below the `---`. I think most people already place it in the correct position because the template tells them so, but we might as well update the contribution guide too.

Update the contribution guide

---

lean.bib

I have tried to sort the entries alphabetically, but could not run bibtool locally.

chore: add papers from ITP 2024

---

templates/extras/calc.md

Removing the senteces "Kevin thinks".
The explanation on how `calc` works internally seems confusing and too complicated for this guide, so I am removing it.

Fix documentation for calc

---

data/courses.yaml

Since the WS24/25 semester, we have been offering practical problems related to Mathlib.

Add MathIR course from Göttingen

---

templates/contribute/naming.md

This PR adds a naming convention for induction/recursion principles.
see also the [zulip topic](https://leanprover.zulipchat.com/#narrow/stream/287929-mathlib4/topic/Induction.20argument.20order)

Induction naming convention

---

templates/contribute/naming.md

This was dropped in the transition from Lean 3.

chore: restore advice on left/right in injectivity lemmas

---

templates/100.html

This matches leanprover-community/mathlib4/19503.

fix: separate multiple authors by ' and ', not a comma

---

make_site.py
templates/100.html
templates/1000-missing.html
templates/1000.html

Depends on https://github.com/leanprover-community/mathlib4_docs/pull/5.
Details of the generated webpage are up for discussion.

feat: add page for tracking the 1000+ theorems list

---

make_site.py
templates/100-missing.html
templates/100.html
templates/1000-missing.html
templates/1000.html

(and move out of templates into make_site.py)
cf. [Zulip](https://leanprover.zulipchat.com/#narrow/channel/113488-general/topic/1000-plus.20theorems.20project/near/492814764)

change logic for which theorems count as formalized

---

make_site.py

The current code includes `<p><a href="None">url</a></p>` for every entry that doesn't have a URL listed.

Avoid including invalid links in 1000.html

---

make_site.py
templates/100-missing.html
templates/100.html
templates/1000-missing.html
templates/1000.html

And display these on the generated webpage as well.
I don't expect the list of theorems with just a statement to grow large, but for some results, this could be useful.
Accompanies https://github.com/leanprover-community/mathlib4/pull/20637; it's better to merge this PR first.

feat: allow statements of theorems in 1000.yaml

---

make_site.py
templates/100-missing.html
templates/100.html
templates/1000-missing.html
templates/1000.html

This matches the `Formalization` type in `make_site.py`, and the mathlib PR https://github.com/leanprover-community/mathlib4/pull/20875.

chore: use 'authors' for the authors field in {Hundred,Thousand}Theorems

---

templates/100-missing.html
templates/1000-missing.html

The previous PR broke the webpage build; I don't understand why. Hopefully, reverting this fixes it.

chore(100,1000.html): remove mention of formalised statements

---

templates/contribute/index.md
templates/queue-redirect.html

Unfortunately bit.ly is going to start forcing free users to click through a page with ads. As an alternative, we'll host a simple redirect page here instead.
I'll update the `#queue` linkifier on Zulip to point to https://leanprover-community.github.io/queue-redirect after this is merged.

add self-hosted #queue redirect

---

data/menus.yaml

Add a link to the Verso project [Mathlib Manual](https://leanprover-community.github.io/mathlib-manual/html-multi/), currently featuring an auto-generated list of all tactics, along with some curated tactic lists.

feat: add link tactic list

---

templates/theories/sets.md

Just a tiny change for clarity, matches the order of the descriptions to that of the functions.

Reorder words in sets.md

---

.gitignore
make_site.py

Per discussion in maintainer's stream. Already tested locally.
See also https://github.com/leanprover-community/mathlib_stats/pull/12, which is now uploading a text file with the number of contributors [here](https://leanprover-community.github.io/mathlib_stats/contributor-count).
(For those with access to the `mathlib-mailmap` repo, [here's](https://github.com/leanprover-community/mathlib-mailmap/blob/7775b1a2644ac5e8cb4749f7926875b849ce6b7c/count) the script that generates the count of contributors).

use mailmap data for contributor count

---

data/menus.yaml

I think it might help users find the reference manual if it's included in the overview of documentation on this site.

feat: add language reference to documentation overview

---

templates/contribute/naming.md

This is a proposal for a naming convention for Prop-valued classes. The proposal is that nouns get `Is` and adjectives do not.

feat: add naming convention for Prop-valued classes

---

templates/mathlib_stats.html

- the first few commits apply autoformatting / JS linting and comment out a function which didn't seem to be used
- the third commit makes it so that the code growth graphs no longer show mathlib3 data points after it was archived nor mathlib4 datapoints from before it existed.
- the last commit removes some commented out code
Before:
After:
Closes #529.

cleanup mathlib_stats.html

---

templates/contribute/index.md

I gave a shot at clarifying this text per the discussion in [Zulip](https://leanprover.zulipchat.com/#narrow/channel/287929-mathlib4/topic/Steps.20after.20first.20approval.20in.20pull.20request.3F)
Some decisions I took:
- Replace the queue-redirect with a link to the queueboard (we might want to update the #queue linkifier and/or this redirect?)
- Tried to avoid saying "reviewer" when it's not about someone in the reviewers team.
- Tried to manage expectations with respect to the review process
Linking the maintainers/reviewers directly from this page might be controversial, since it could lead to increases in direct messages to them. I tried to mitigate this by adding the remark about the PR reviews stream. I do think it is worthwhile being clear about who has what role, because (as per …

Clarify review process

---

templates/install/project.md

See [#new members > Outdated quickstart instructions? @ 💬](https://leanprover.zulipchat.com/#narrow/channel/113489-new-members/topic/Outdated.20quickstart.20instructions.3F/near/512862872) . Can someone else confirm that the instructions already create this directory?

fix: apparently the directory is already created

---

templates/get_started.md
templates/install/debian.md
templates/install/debian_details.md
templates/install/linux.md
templates/install/macos.md
templates/install/macos_details.md
templates/install/project.md
templates/install/windows.md

I am extremely fond of the community installation pages. For years they have helped me get new users up and running, on all platforms. The pages were written back in the Lean 3 days when there was very little official support for this sort of thing, and the community web pages were playing a key role in the installation and onboarding process. 
But things move on. I recently got a new laptop and I installed Lean by following the instructions on the lean-lang website; it was completely pain-free and I never even had to open a terminal. My impression from the undergrad maths community is that this is what most people want. I think that nowadays we should be pointing new users to the official installation process rather than our detailed command-line explanations.
There will always be some …

Direct the user wanting to install Lean to the official website

---

templates/contribute/naming.md

Fixes an oversight in #624.
The current page looks like this, which is definitely not intended.

fix(naming): use inline equation

---

data/menus.yaml

These ought to be augmented with a section on AI usage and spam (as was posted on zulip); this can happen in a follow-up PR.
-------
Note: I am not sure if linking to a subsection of a page actually works this way. Testing welcome (last time I tried to set up a local testing environments, things failed miserably, so I cannot do so myself).

feat: add a sidebar entry linking to the community guidelines

---

templates/contribute/naming.md

Clarify a detail of the `≤ `/`<` naming convention.

feat: describe how to order `le`/`lt` and `ge`/`gt`

---

templates/contribute/style.md

This PR refers to the linter appearing in [mathlib4#25236](https://github.com/leanprover-community/mathlib4/pull/25236).

Add style guide about disallowing empty lines in commands

---

templates/1000.html

Not sure why I missed this in #576.

1000.html: link IDs for unproved theorems to their wikidata page

---

data/menus.yaml
templates/get_started.md

In [this](https://leanprover.zulipchat.com/#narrow/channel/113488-general/topic/Mathlib.2Edmg.20installation.3F/near/525533445) Zulip thread, Alex Kantorovich raises the issue that the installation header on the main page is somewhat unclear.
* Most glaringly, there is a a subheading under "installation" which says (no installation).
* The "Getting Started" entry actually has installation instructions, but only in the second paragraph, and it is unclear whether "Getting Started" will lead to installation instructions or a generic tutorial.
This PR proposes:
* Renaming the heading from "Installation" to "Use Lean" which is maybe a more accurate description of what the links in this subheading help you do.
* Renaming the "Getting Started" heading and file to "Set up Lean", which is more …

chore: change installation side menu to make more sense

---

data/menus.yaml
templates/get_started.md
templates/index.html

* Remove `lake` from side menu (these are legacy instructions, made obsolete by the installation guide. They are still accessible through `get_started`)
* Add a direct link to `quickstart` in the sidebar
* Rename "set up Lean" to "More options". The idea of the "more options" is that it also repeats the other two suggestions in the sidebar, and gives a better description of the online options.
* Link to https://live.lean-lang.org/ on the "more options" page
* Prefer Codespaces over Gitpod on the "more options" page (I already preferred it before, but now Gitpod is deprecated we definitely should do this)
* Remove all the text about projects. That is now completely obsolete with the quickstart guide, which will ask you to install a project like Mathlib or Mathematics in Lean.
EDIT:
* On …

update menu and installation instructions

---

templates/extras/pitfalls.md

A common gotcha on the Zulip is people using `foo := bar` in structure fields to mean "`foo` is defined to be equal to `bar`" rather than understanding that this is a default value.
Also a couple of unrelated minor changes.

feat: add warning about default values of structure fields
